publishdir = "public"  # 生成的静态文件将存放在 public 文件夹
static = "/static"  # 静态文件的路径
builddrafts = false  # 不构建草稿文件
# 将此替换为你的网站 URL
baseurl = "http://example.org/"  # 网站的基础 URL
canonifyurls = true  # 启用 URL 规范化
theme = "hugo-academic-group"  # 使用的 Hugo 主题
title = "医学大数据分析与转化实验室"  # 网站标题
math = true  # 启用数学公式支持
copyright = "&copy; Ahmu-LMBDAT, 2024"  # 版权信息

[taxonomies]
category = "categories"  # 文章的分类
tag = "tags"  # 文章的标签

[params]
  description = "医学大数据分析与转化实验室"  # 网站描述
  author = "yangfei"  # 作者
  email = "yangfei@ahmu.edu.cn"  # 邮箱
  address = "安徽省合肥市瑶海区唐河路安徽医科大学东校区"  # 地址

  slogan = "安徽医科大学生物医学工程学院"  # 标语
  slogan_text = "医学大数据分析与转化实验室"  # 标语文本

  [[params.slogan_columns]]
    title = "关于我们"  # 第一栏标题
    text =  "建设具有医学特色的精准医学大数据平台，整合现有医疗数据资源，按照医疗数据特性，对数据进行标准化处理和入库，构建医疗数据知识仓库。基于大数据挖掘、自然语言处理和机器学习等技术，进行面向给药、医学影像、放疗的精准治疗研究。将人工智能与传统医学方法紧密结合，科学解读与人体机能和疾病相关的生物医学大数据，在精准医学大数据平台实现“在正确的时间，为正确的人，使用正确的药物”的精准医疗服务。"  # 第一栏描述
    link = "/about"  # 详细信息链接
    link_text = "查看详情"  # 链接文本
    weight = 1  # 权重，用于菜单排序
  
  [[params.slogan_columns]]
    title = "我们的任务"  # 第二栏标题
    text = "在医学、数据科学和生物医学工程交叉领域进行具有变革性的研究是我们的使命。我们致力于运用大数据的力量来推动医疗创新，从基础研究延伸至临床应用。我们的首要目标在于开创领先的分析方法和技术，将复杂的医学数据转化为直接影响患者护理和公共健康的可操作见解。通过跨学科合作和对卓越的追求，我们旨在推动医学数据分析的前沿，最终促进改善诊断、治疗和医疗服务的发展。"  # 第二栏描述
    link = "/mission"  # 详细信息链接
    link_text = "查看详情"  # 链接文本
    weight = 2  # 权重
  
  [[params.slogan_columns]]
    title = "我们的目标"  # 第三栏标题
    text = "为实现使命，我们采用交叉学科方法解决医学大数据分析与转化挑战。我们整合临床记录、生物标记物和影像学数据，利用高性能计算平台开发算法和模型，应用机器学习和人工智能技术发现新方法，结合生物医学工程开发医疗设备和治疗方法。最后，与临床医生合作验证成果，将其应用于实际临床环境。综合这些方法，我们致力于带来医学大数据分析与转化领域的科学发现，实现对患者和公共健康的积极影响。"  # 第三栏描述
    link = "/approach"  # 详细信息链接
    link_text = "查看详情"  # 链接文本
    weight = 3  # 权重

  # Selected Publications section.
  [params.publications_selected]
    detailed_list = true  # 是否显示详细的论文列表
    title = "Selected Publications"  # 标题
    subtitle = ""  # 子标题（为空）

  # Publications section.
  # 如果 `content/publication/` 中有论文，将显示此部分
  [params.publications]
    count = 5  # 显示 5 篇论文
    detailed_list = false  # 不显示详细列表
    title = "论文"  # 标题
    subtitle = ""  # 子标题（为空）
    str_all = "更多的论文"  # 更多论文的链接文本

  # Posts section.
  # 如果 `content/post/` 中有文章，将显示此部分
  [params.posts]
    count = 2  # 显示 2 篇文章
    title = "博客"  # 标题
    subtitle = ""  # 子标题（为空）
    str_all = "更多的推文"  # 更多文章的链接文本
    str_read_more = "查看详细"  # 查看文章详细信息的链接文本

  # Projects section.
  # 如果 `content/project/` 中有项目，将显示此部分
  [params.projects]
    title = "项目"  # 标题
    subtitle = ""  # 子标题（为空）
    count = 3  # 显示 3 个项目
    str_all = "More Projects"  # 更多项目的链接文本
  
  # Vacancies section
  # 如果 `content/vacancy` 中有职位空缺，将显示此部分
  [params.vacancies]
    title = "职位"  # 标题
    subtitle = ""  # 子标题（为空）
    count = 3  # 显示 3 个空缺职位
    str_all = "More Vacancies"  # 更多职位的链接文本


  # Contact section.
  [params.contact]
    enable = true  # 启用联系方式部分
    title = "联系方式"  # 标题
    subtitle = ""  # 子标题（为空）
    autolink = false  # 是否自动链接邮箱和电话

  # Navigation Links
  # `weight` 参数定义了链接显示的顺序

  [[menu.main]]
      name = "首页"  # 菜单项名称
      url = "/#top"  # 链接 URL
      weight = 1  # 权重

  [[menu.main]]
      name = "研究"  # 菜单项名称
      url = "/research"  # 链接 URL
      weight = 2  # 权重

  [[menu.main]]
      name = "论文"  # 菜单项名称
      url = "/#publications"  # 链接 URL
      weight = 3  # 权重

  [[menu.main]]
    name = "项目"  # 菜单项名称
    url = "/#projects"  # 链接 URL
    weight = 4  # 权重

  [[menu.main]]
      name = "成员"  # 菜单项名称
      url = "/#members"  # 链接 URL
      weight = 5  # 权重

  [[menu.main]]
      name = "博客"  # 菜单项名称
      url = "/#posts"  # 链接 URL
      weight = 6  # 权重

  [[menu.main]]
      name = "联系方式"  # 菜单项名称
      url = "/#contact"  # 链接 URL
      weight = 7  # 权重
